# Generated by Django 4.0.4 on 2022-04-16 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastebin_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('paste_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paste_snap', models.JSONField()),
                ('paste_time', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
            ],
        ),
    ]
