# Generated by Django 4.0.4 on 2022-04-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_backend', '0003_alter_paste_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expire_time',
            field=models.IntegerField(),
        ),
    ]
